### ISSUE TITLE
Protobuf

### ISSUE THREAD

**Issue by jantoebes** [scalapenos/stamina#12]
If you will invent your own serialization-codec (DefaultPersistedCodec), than i propose to put the fixed attributes at the beginning. 

Why not using protobuf for the defaultpersistedcodec. It is realy easy to integrate it with scala https://code.google.com/p/protobuf-scala/ and next to it:
1. Proven technology, optimized and specific for this kind of situations.
2. You don't have to invent your own 'protocol' as you do here.
3. Because you use protobuf if will be easier for other tools which want to sniff the data in the cassandra database (i know, most of the times you shouldn't, but if your application doesn't want to startup, you have to inspect it).

**Comment by agemooij** [comment]
Protobuf would add some generated sources that IMHO are not necessary. The binary encoding here is actually very close to how protobuf encodes stuff. The only thing I left off was variable integer encoding. These encoding choices are very much standard approaches.

How do you think Protobuf will help people read raw data from their databases? Do you think a separate stamina-utils project would be useful that would contain tools for reading raw encoded data? That way you solve more problems for those users than just giving them slightly more info about how the envelope containing their serialized data was encoded.

**Comment by raboof** [comment]
I think adding Protobuf might make stamina-core a bit too complicated. 

It could be neat to have a ProtobufPersistedCodec in stamina-protobuf (and JsonPersistedCodec in stamina-json, etc etc) that you can easily plug in when you want to go that route.

**Comment by agemooij** [comment]
Akka 2.4 will natively support String-based manifests that we can use to store our metadata (ie. the key and the version) so the Codec envelope will be there mostly for backwards compatibility, for instance to be able to read back older data serialized with Stamina's predecessors in the project that gave birth to Stamina. Those predecessors used a slightly different envelope encoding, making it necessary to at least support the idea of Codecs so those code bases can migrate to Stamina.

If Akka 2.4 is released on time we might even go full 2.4-only with Stamina while allowing those older projects to write their own Serializer subclass wrapper for Stamina persisters using a backwards compatible codec.

Closing this issue for now.
