### ISSUE TITLE
Replace the spray-json macro with spray-json-shapeless

### ISSUE THREAD

**Issue by agemooij** [scalapenos/stamina#21]
Stamina-json contains a simple macro that will auto-generate a `RootJsonFormat[T]` for you but it has some hard limits in that it won't deal well with cyclic nested hierarchies or sealed trait families.

Spray-json-shapeless looks very promising but there might be some inherent limitations according to its creator so we'd have to test it out, preferably on the example application for a better, more real-world split between where the domain classes are defined and where the json formats are coming from..

**Comment by jheijkoop** [comment]
Is this fixed in master?

**Comment by agemooij** [comment]
Fixed on master by #31
