### ISSUE TITLE
Depend on new Akka 2.4 features?

### ISSUE THREAD

**Issue by agemooij** [scalapenos/stamina#23]
Akka 2.4 M2 has some interesting features, such as:
- the StringBased serializer that would allow us to encode the key-version in the akka metadata instead of having to create our own binary envelope
- the new 2.4-M2 concept of event adapters: http://doc.akka.io/docs/akka/2.4-M2/scala/persistence.html

This would break backwards compatibility with Akka 2.3 though, and 2.4 is not out yet and might not be out for a while.

**Comment by guersam** [comment]
IMHO, as Akka 2.4-RC1 is released and it claims binary compatibility with 2.3, it would make things simple to only support Akka >= 2.4 with those new features.

**Comment by agemooij** [comment]
Stamina is now based on Akka 2.4
