### ISSUE TITLE
A type for key would be nice. (instead of String)

### ISSUE THREAD

**Issue by RayRoestenburg** [scalapenos/stamina#4]
Same for version. Int is a bit much for that as well. And you don't want negative values right?

**Comment by agemooij** [comment]
Using a type for keys instead of a String sounds ok but I thought about it a bit a while ago and I couldn't come up with any good reason why you'd want that. Care to suggest one?

Since the only version numbers are generated internally through type-safe Vn classes, the Int doesn't seem like such a huge risk of generating negative versions. What would be the alternative?

**Comment by RayRoestenburg** [comment]
Like a nonemptystring nothing fancy

**Comment by agemooij** [comment]
I looked around and there doesn't seem to have been anyone online who has created a compile-time checker for non-emptiness in Strings.

The easy answer would be to just check at runtime but where would be the fun in that? NonEmptyString macro coming up I guess... PRs welcome ;)

**Comment by agemooij** [comment]
How about this:

![screen shot 2015-02-15 at 11 47 45](https://cloud.githubusercontent.com/assets/46568/6202980/99ea7490-b508-11e4-8459-8736ca19730e.png)

Almost done with the commit and I learned me some macro stuff again ;)

**Comment by agemooij** [comment]
``` scala
  case class Key(value: String) {
    import java.nio.charset.StandardCharsets.UTF_8
    def getUtf8Bytes: Array[Byte] = value.getBytes(UTF_8)
    override def toString = value
  }

  object KeyMacro {
    import scala.reflect.macros.Context

    def nonEmptyStringToKey(c: Context)(in: c.Tree): c.Tree = {
      import c.universe._
      val q"${ s: String }" = q"${in}"
      if (s.isEmpty) c.abort(c.enclosingPosition, s"Persistence keys must be non-empty!")
      else q"Key($in)"
    }
  }

  implicit def nonEmptyStringToKey(in: String): Key = macro KeyMacro.nonEmptyStringToKey
```

Notice the unlifting to get back a String to check for emptiness. This will be in stamina soon.

**Comment by agemooij** [comment]
I've been trying to get the Macros to be backwards compatible with 2.10 but that's pretty damn tricky it seems :cry:

**Comment by agemooij** [comment]
Closing this for now. There doesn't seem to enough reason or interest for typing persister keys. Perhaps the public beta release will bring back similar requests at a later date.
