### ISSUE TITLE
Type class macro for versioning?

### ISSUE THREAD

**Issue by RayRoestenburg** [scalapenos/stamina#5]

**Comment by agemooij** [comment]
Do you mean a macro to make `V3` automatically implement `VersionInfo[V3](3) with Migratable[V3] with IsNextAfter[V3, V2]`

Interesting idea, but I wonder how to make the necessary exception for V1. Any more specific implementations hints?

**Comment by RayRoestenburg** [comment]
It was a bit of a brainfart but yes, so you dont have a problem at 51
theres a typeclass macro blog post on typelevel maybe applicable maybe not

**Comment by agemooij** [comment]
If I wanted to prevent problems at 51, which is just a random number where I thought "good enough for most people", I'd have to be able to generate new types purely by naming convention. As in: "it starts with V and ends with a number and the class doesn't exist so please generate it on the fly and make it implement these three type classes"

Now you're really asking too much from the Scala compiler I think...

My plan was to wait for the first pull request that asks for versions higher than 50 and take it from there.

**Comment by agemooij** [comment]
Not possible on 2.10/2.11 without macro-paradise. For now I'm closing this since I don't want to force the main target user group (i.e. 2.11 users) to use macros-paradise.
