### ISSUE TITLE
Use of .getSimpleName in StaminaTestKit throws

### ISSUE THREAD

**Issue by krivachy** [scalapenos/stamina#52]
If we have `Persistable` classes nested in objects and we want to use `StaminaTestKit` then it throws an exception. This is a known bug in Scala: https://issues.scala-lang.org/browse/SI-2034 (look at duplicate issues)

```
[info] Exception encountered when attempting to run a suite with class name: org.scalatest.DeferredAbortedSuite *** ABORTED ***
[info]   java.lang.InternalError: Malformed class name
[info]   at java.lang.Class.getSimpleName(Class.java:1330)
[info]   at stamina.testkit.StaminaTestKit$PersistableSample.toString(StaminaTestKit.scala:11)
[info]   at java.lang.String.valueOf(String.java:2994)
[info]   at java.lang.StringBuilder.append(StringBuilder.java:131)
[info]   at scala.StringContext.standardInterpolator(StringContext.scala:125)
[info]   at scala.StringContext.s(StringContext.scala:95)
[info]   at stamina.testkit.StaminaTestKit$TestablePersisters.stamina$testkit$StaminaTestKit$TestablePersisters$$generateRoundtripTestFor(StaminaTestKit.scala:28)
[info]   at stamina.testkit.StaminaTestKit$TestablePersisters$$anonfun$generateTestsFor$1.apply(StaminaTestKit.scala:21)
[info]   at stamina.testkit.StaminaTestKit$TestablePersisters$$anonfun$generateTestsFor$1.apply(StaminaTestKit.scala:20)
[info]   at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
```

I think the only solution would be to not call `.getSimpleName` [here](https://github.com/scalapenos/stamina/blob/master/stamina-testkit/src/main/scala/stamina/testkit/StaminaTestKit.scala#L11), but rather force the use of description.

**Comment by agemooij** [comment]
Thanks for reporting @krivachy! Could you perhaps post a small code example? I don't precisely understand what you mean by 

> `Persistable` classes nested in objects

@raboof you know more about the testkit than me... what would be the alternative for a good sample name?

**Comment by raboof** [comment]
I haven't dived into it, but I suspect we could replace it with the `SimpleClassNameExtractor` from https://github.com/spray/spray-json/issues/186

**Comment by krivachy** [comment]
Oh boy, you guys are responsive! 😃  Here's the sample:

```
package demo

import demo.SampleActor.InternalEvent.SomeMessage
import org.scalatest.WordSpecLike
import spray.json.{RootJsonFormat, _}
import stamina.Persisters
import stamina.testkit.StaminaTestKit
import stamina.json._

object SampleActor {
  sealed trait InternalEvent
  object InternalEvent {
    final case class SomeMessage(s: String) extends InternalEvent
  }
}

object Serializer extends DefaultJsonProtocol {
  implicit val format: RootJsonFormat[SomeMessage] = jsonFormat1(SomeMessage)
  val eventPersister = persister[SomeMessage]("SomeMessage")
}

class SampleTest extends WordSpecLike with StaminaTestKit {

  val persisters = Persisters(Serializer.eventPersister)
  "The Event persister" should {
    persisters.generateTestsFor(
      sample(SomeMessage("string"))
    )
  }
}
```

I guess this comes from my personal style of declaring the Events for that actor in it's companion object and even in that scoping everything into a `sealed trait`'s companion object.

**Comment by krivachy** [comment]
Yes, the `SimpleClassNameExtractor` would solve it. Let me cobble together a PR.

**Comment by agemooij** [comment]
I  don't have time to run this code at the moment but I've seen that pattern used before so there is nothing very unusual about it, although I usually wouldn't use the external `SampleActor` object and I would usually put the implicit formats and persisters in the `InternalEvent` object to prevent having to explicitly import them.
