### ISSUE TITLE
stamina-testkit fails when file in tmp directory already exists 

### ISSUE THREAD

**Issue by rwiskerke** [scalapenos/stamina#58]
Sorry for the short description, but here we go:

In this line the the bytearray is saved to disk:
https://github.com/scalapenos/stamina/blob/d9984aaa893f8b164d55002f8a2305e0a272e0d4/stamina-testkit/src/main/scala/stamina/testkit/StaminaTestKit.scala#L84

It only supplies the `StandardOpenOption.CREATE` and if the file already exists it will just overwrite the amount of bytes it needs to write. If the old file contained more bytes than you're writing, it will leave them on disk, effectively appending them to your output.

It would be nice to either use `CREATE_NEW` which fails if the file already exists OR pass an additional argument `TRUNCATE_EXISTING` which will make sure the existing file is truncated before writing to it. BTW the default is CREATE + TRUNCATE_EXISTING, so removing the `CREATE` altogether would work fine too.

**Comment by agemooij** [comment]
Thanks for reporting this. I'd go for explicitly setting it to `CREATE + TRUNCATE_EXISTING` instead of relying on the default. But that's just my defensive coding OCD side talking :)

Would you have time to create a PR for this?

**Comment by rwiskerke** [comment]
@agemooij Depends on how well tested you want it. Do you require a specific testcase or are passing (existing) tests enough?

**Comment by agemooij** [comment]
I would argue that this fixes a bug in our usage of file creation so we  don't need to test that the file creation api works as configured.

**Comment by raboof** [comment]
wow that's subtle. thanks for spotting.

**Comment by Philippus** [comment]
I think this was fixed in https://github.com/scalapenos/stamina/pull/60 and https://github.com/scalapenos/stamina/pull/70.

**Comment by rwiskerke** [comment]
I agree @Philippus
