### ISSUE TITLE
Release for scala 2.12

### ISSUE THREAD

**Issue by kkafara** [scalapenos/stamina#66]
Hi,
as in subject, is there a plan to release stamina for scala 2.12?

**Comment by raboof** [comment]
Good idea! Unfortunately it seems the base64 dependency we have is not yet published for 2.12.

I suppose we could either shift to another way of doing base64 or help get them to 2.12 (https://github.com/softprops/base64/pull/4)

**Comment by kkafara** [comment]
From what I see target JVM is already set to `1.8`, maybe just `java.util.Base64` could be used?
Or am I missing something and it can't be used?

**Comment by kkafara** [comment]
I guess if you rebase it now it should pass 😄

**Comment by knirski** [comment]
I think it can be closed now, as `0.1.3` is already released for scala 2.12.

**Comment by agemooij** [comment]
Yes, and I just released version 0.1.4 with lots of version upgrades.
Stamina now depends on Akka 2.5.8 and is compiled against Scala 2.12.4 (and 2.11.11)
