### ISSUE TITLE
StaminaTestKit shouldn't use `java.lang.Class.getSimpleName`

### ISSUE THREAD

**Issue by kkafara** [scalapenos/stamina#69]
Usage of `java.lang.Class.getSimpleName` is dangerous and throws `InternalError("Malformed class name")` for `case class`es that are defined inside scala `object`s. `java.lang.Class.getName` should be used instead.  
If you want `simpleName` for some reason then it should be wrapped with `Try` with fallback to `getName`.  
I'm happy to make PR, please decide if we switch to `getName` or we do `simpleName` with fallback to `getName`.

**Comment by kkafara** [comment]
I see that it's already fixed in master, that's great.
Can you think about releasing new version soon? Or at least a bug fix with this fix only?

**Comment by raboof** [comment]
Yeah we should probably finish up #68 and make a next 0.1.x release
