### ISSUE TITLE
stamina-avro and stamina-pickling

### ISSUE THREAD

**Issue by jantoebes** [scalapenos/stamina#7]
What do you mean with stamina-avro and stamina-pickling in your documentation? Good to give a short description. 

File: https://github.com/scalapenos/stamina/edit/master/README.md#10

**Comment by agemooij** [comment]
Both Avro and Pickling are serialization libraries that I'd like to try to build plugins for. I made the assumption that most people looking for a serialization solution have already heard of them but point taken ;)

**Comment by raboof** [comment]
a quick hyperlink should be sufficient :)

**Comment by agemooij** [comment]
Removed these from the README because they are not going to be part of the first public beta release.
