### ISSUE TITLE
Release version v0.1.5

### ISSUE THREAD

**Issue by raboof** [scalapenos/stamina#76]
I guess we should set up releasing from travis (perhaps with sbt-ci-release)

@larochef would you be interested in joining as a maintainer and looking into this?

**Comment by larochef** [comment]
Looks like it'd be the best option.

I can have a look at the releasing, it looks really simple (even though this stuff almost always requires a few fails before being all good). How will it work with travis and sonatype? Will you add the pgp and sonatype variables in Travis?

**Comment by raboof** [comment]
> Looks like it'd be the best option.

Great! Welcome!

> How will it work with travis and sonatype? Will you add the pgp and sonatype variables in Travis?

Perhaps we should just give you any access you might need to do it? If that's cumbersome for some reason we'll take care of it :+1:

**Comment by larochef** [comment]
Thx !

So I guess you'll need: 
- to give rights on the repo
- to open an issue on the sonatype bugtracker (https://issues.sonatype.org) and ask to give me the rights on the `com.scalapenos` group (or else we should move stamina to some other suitable place). I'm not sure but maybe it can be possible to restrict to `com.scalapenos.stamina` My username on sonatype is `flaroche`
- to make sure I have the correct rights in Travis once you have added me on the github repo

I guess with all of this, I shouldn't need more.

**Comment by raboof** [comment]
@agemooij can you add @larochef to the maintainers team at https://github.com/orgs/scalapenos/teams/stamina-maintainers/members ? Looks like I don't have permission for that

I think you can open the sonatype issue yourself, just link to this thread ;)

**Comment by larochef** [comment]
I have created the sonatype issue, https://issues.sonatype.org/browse/OSSRH-53122
They are asking that someone with the write access comments the issue to confirm it.

@raboof can you do it?

**Comment by larochef** [comment]
@raboof @agemooij the maven central access should be fine, could you see to give me access to the repository ? (I guess the travis access will come with it)

**Comment by raboof** [comment]
I added you as a 'collaborator' for now to get you unstuck - the neat way would be to add you to the org in the "Stamina Maintainers" group, but I think only @agemooij can do that.

**Comment by agemooij** [comment]
@larochef  I added you to the contributors team, which now also has `Maintainer` permissions. If you end up requiring full `Admin` permissions, please let me know.

**Comment by larochef** [comment]
#77 should do the job, we'll then have to push to `v0.1.5` to release it.

@raboof  @agemooij  can you have a look at it before it gets merged?

**Comment by larochef** [comment]
That's quite impressive, it worked on first time!!
I guess it's the first time I set up the releases on first time, I usually need a few commits to have all fine.

sbt-ci-release is really great, I didn't know about it, but I guess I'll use it with all my other projects I push on maven central!

**Comment by raboof** [comment]
Yeah it's pretty great!

**Comment by larochef** [comment]
I guess this issue can be closed, since the released is now available.

**Comment by raboof** [comment]
Congratulations on your first stamina release :tada: :confetti_ball: !
