### ISSUE TITLE
Create release with scalatest update

### ISSUE THREAD

**Issue by idserda** [scalapenos/stamina#79]
Would it be possible to create a release that has scalatest >= 3.1.0 as a dependency (e.g. current master)? Thanks!

**Comment by agemooij** [comment]
Hi @idserda . I haven't been active on this project for quite some years but if you could submit a PR with the relevant dependency upgrades I might find some time to merge it and release an updated version.

Just out of curiosity, what specifically is the problem with Scalatest in combination with stamina that is causing you issues? Wouldn't sbt just override the Stamina version with your version? Are there binary incompatibilities?

**Comment by idserda** [comment]
Scalatest >= 3.1.0 is binary incompatibly with any previous version. The upgrade to this version has already been made in this project, but it was never released. Our projects that have updated scalatest can't use stamina at the moment.

Scalatest 3.2.0 has also been released in the meantime, I've created a PR to upgrade to this version. Would be great if you could have a look and release a version with this dependency updated.

**Comment by raboof** [comment]
Releasing from master now.

**Comment by raboof** [comment]
should be on its way to maven central (monitor i.e. https://repo1.maven.org/maven2/com/scalapenos/stamina_2.13/).

Was much easier than the RELEASE.md suggested, updating that in #81

**Comment by idserda** [comment]
Great! Thanks @raboof
