### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by jantoebes** [scalapenos/stamina#8]
I think the structure of the readme can be improved. 
1. There are very long lines (especially at bullet points) which makes it hard to figure out the exact point you want to make. For example, the sections 'goals/approach' or 'stamina'. IMO opinion you can strip most of the lines so it will be very explicit. Next to it, not everybody is familiar with the term AST.
2. Structure. Begin with a short introduction (just as 4/5 lines) of the functionality of stamina. Just like in https://github.com/jrudolph/json-lenses. Take the line in chapter 'why'.
3. Don't you mean with 'Goals/approach' just the 'roadmap'? You can move the current status to this area so it will be very clear what is done yet and will be done.
4. Introduce an 'example' chapter where you put in more examples.
5. In the chapter 'So what's wrong with Akka Persistence?' don't go too wild in this chapter. Make it more powerfull by shorten your points.
6. I think it would be really valuable if you can put your ideas/outline for the cases when there is no 1 to 1 relation between old and new event. For example, an event is split in two)or when there should be done some business processing before merging to the new event (aggregate information from an extra file, for instance)

**Comment by agemooij** [comment]
Closing for now. Points have either been taken on board or already made it into the README
